services:
  overleaf:
    build: .
    image: overleaf-custom:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      OVERLEAF_APP_NAME: Overleaf
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      OVERLEAF_INVITE_TOKEN_SECRET: "j487DJsTltetZvlu7J3PYWzTGKH0d7cxuqpshattOiDkKdMqlKD0Km0e8eiiJVpe"
    volumes:
      - overleaf_data:/var/lib/overleaf
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  overleaf_data:
  mongo_data:
  redis_data:
